POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Oh, it was the emo heart after all but it didnt look like that in rest extension",
    "author": "Alina",
    "url": "http://example.com",
    "likes": 7
}
